before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby  
rvm:
  - "2.2.0"
services:
  - mongodb
addons:
  code_climate:
    repo_token: 4cd5f188e05e9380e0a15e48fd1ad1226a5178d7a394966942dcacc11e97140a
script:
  - cd dummy
  - ln -s ../.git .git
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=4cd5f188e05e9380e0a15e48fd1ad1226a5178d7a394966942dcacc11e97140a bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=4cd5f188e05e9380e0a15e48fd1ad1226a5178d7a394966942dcacc11e97140a bundle exec cucumber
