development:
 adapter: postgresql
 database: voluntary_text_creation_development
 encoding: unicode
 username: root
 password:
 encoding: unicode

test: &TEST
 adapter: postgresql
 encoding: unicode
 database: voluntary_text_creation_test
 pool: 5
 username: root
 password:
 
production:
  adapter: postgresql
  encoding: unicode
  database: voluntary_text_creation_production
  encoding: utf8
  pool: 5
  host: localhost
  username: voluntary_text_creation
  password:
  
cucumber:
 <<: *TEST